spring.application.name=contactlistapi

# Permite acesso externo a API pelo IP da rede
server.address=0.0.0.0

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.h2.console.settings.web-allow-others=true

# Datasource
spring.datasource.url=jdbc:h2:file:/root/contactlist
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

# Trata telas de erro do Spring Boot 3
server.error.include-stacktrace=never
server.error.include-message=never

# Formatacao de Datas
spring.mvc.format.date=dd/MM/yyyy
spring.mvc.format.date-time=dd/MM/yyyy HH:mm:ss
spring.mvc.format.time=HH:mm:ss

